pipeline {

  agent {
    node {

    label 'slave'
}

}
  environment {
    DOCKERHUB_CREDENTIALS = credentials('dockerhub')
    REPO_NAME = "vatss90/nginx_new"
    IMAGE_TAG = "${params.IMAGE_TAG}"
  }
  stages {
    stage('cloning') {
      steps {
        script {
            checkout scm  

      }
}    

}
    stage('Print IMAGE TAG') {
      steps {
       
       withCredentials([gitUsernamePassword(credentialsId: 'vatss90')]) { 

sh """ 
ls  
git config --global user.name 'jenkinsUser' 
git config --global user.email 'jenkins@acefone.com' 
git log -1 
git fetch origin main
git checkout main
git pull origin main
sed -i 's/\\(tag: \\)[^ ]*/\\1${IMAGE_TAG}/' nginxchart/values.yaml 
git add nginxchart/values.yaml
git commit -m "Image updated with commit ID: ${IMAGE_TAG}" 
git push origin main
        """
      }
  }

 }
 }
                           
 } 
