pipeline {

  agent {
    node {

    label 'slave'
}

}
  environment {
    DOCKERHUB_CREDENTIALS = credentials('dockerhub')
    REPO_NAME = "vatss90/nginx_new"
    IMAGE_TAG = "${params.IMAGE_TAG}"
  }
  stages {
    stage('cloning') {
      steps {
        script {
            checkout scm  

      }
}    

}

    stage('Print IMAGE TAG') {
      steps {
        sh """
        git fetch origin main
        git checkout main
        git pull
        sed -i 's/\\(tag:\\)[^ ]*/\\1${IMAGE_TAG}/' nginxchart/values.yaml
        git add nginxchart/values.yaml
        git commit -m "imageupdate tag ${IMAGE_TAG}"
        git push origin

        """
      }
    }

  
}


  }
                           
  
