indexHtmlConfigmap:
  indexHtml: |-
    <html>
    <h1>Welcome sunil helloa...ss. </h1>
    </br>
    <h1>Hi! This is a configmap Index file </h1>
    </html
kubernetesClusterDomain: cluster.local
nginxDeployment:
  nginx:
    image:
      repository: vatss90/nginx_new
      tag: c1b6863
  replicas: 2
nginxService:
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
