apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginxchart.fullname" . }}-index-html-configmap
  labels:
  {{- include "nginxchart.labels" . | nindent 4 }}
data:
  index.html: {{ .Values.indexHtmlConfigmap.indexHtml | toYaml | indent 1 }}