apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginxchart.fullname" . }}-nginx-service
  labels:
  {{- include "nginxchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginxService.type }}
  selector:
    app: nginx
  {{- include "nginxchart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.nginxService.ports | toYaml | nindent 2 -}}